ctid:
  image: xivo/ctid
  volumes:
    - ./config/ctid/conf.d:/etc/xivo-ctid/conf.d
    - ./config/ctid/key.yml:/tmp/xivo-ctid-key.yml
  extra_hosts:
    - xivo:${XIVO_HOST}
  environment:
    - XIVO_UUID=${XIVO_UUID}
lb:
  image: xivo/lb-consul-template
  ports:
    - "5003:5003"
    - "9495:9495"
    - "1936:1936"
  expose:
    - "5003"
    - "9495"
    - "1936"
  container_name: lb
  environment:
    - CONSUL_TOKEN=${CONSUL_TOKEN}
  command: ["-consul", "${CONSUL_HOST}:${CONSUL_PORT}", "-log-level", "debug", "-config", "/config/template.hcl"]
