ctid:
  image: xivo/ctid
  volumes:
    # With my shared directory on docker-mahcine
    #- /shared/ctid-scale/config/ctid/conf.d:/etc/xivo-ctid/conf.d
    #- /shared/ctid-scale/config/ctid/key.yml:/tmp/xivo-ctid-key.yml
    # Without docker-machine
    - ./config/ctid/conf.d:/etc/xivo-ctid/conf.d
    - ./config/ctid/key.yml:/tmp/xivo-ctid-key.yml
  container_name: ctid
  extra_hosts:
    - xivo:192.168.1.124
lb:
  image: xivo/lb-consul-template
  ports:
    - "5003:5003"
    - "9495:9495"
    - "1936:1936"
  expose:
    - "5003"
    - "1936"
  container_name: lb
