ctid:
  image: xivo/ctid
  volumes:
    - ./config/ctid/conf.d:/etc/xivo-ctid/conf.d
    - ./config/ctid/key.yml:/tmp/xivo-ctid-key.yml
  extra_hosts:
    - xivo:192.168.1.124
lb:
  image: xivo/lb-consul-template
  ports:
    - "5003:5003"
    - "9495:9495"
    - "1936:1936"
  expose:
    - "5003"
    - "9495"
    - "1936"
  container_name: lb
  command: ["-consul", "192.168.1.124:8500", "-log-level", "debug", "-config", "/config/template.hcl", "-token", "9b5077e7aebe5924e6ad2d7a75c614e9f705cac73eb5c0a6fa9be8c428b6f1f9"]
