# Rest API
rest_api:
  http:
    listen: 0.0.0.0

# Agentd
agentd:
  host: xivo
  verify_certificate: False

# Provd
provd:
  host: xivo

# Dird (Directory daemon) connection informations.
dird:
  host: xivo
  verify_certificate: False

# xivo-auth (authentication daemon) connection informations.
auth:
  host: xivo
  key_file: /tmp/xivo-ctid-key.yml
  verify_certificate: False

# Event bus (AMQP) connection informations.
bus:
  host: xivo
  username: xivo
  password: xivo

# Consul configuration
consul:
    scheme: https
    host: xivo
    verify: False
    token: 9b5077e7aebe5924e6ad2d7a75c614e9f705cac73eb5c0a6fa9be8c428b6f1f9

service_discovery:
  advertise_address: ctid
  check_url: http://ctid:9495/0.1/infos

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@xivo/asterisk

# AMI asterisk
ipbx_connection:
  ipaddress: xivo
