# Rest API
rest_api:
  http:
    listen: 0.0.0.0

# Agentd
agentd:
  host: xivo
  verify_certificate: False

# Provd
provd:
  host: xivo

# Dird (Directory daemon) connection informations.
dird:
  host: xivo
  verify_certificate: False

# xivo-auth (authentication daemon) connection informations.
auth:
  host: xivo
  key_file: /tmp/xivo-ctid-key.yml
  verify_certificate: False

# Event bus (AMQP) connection informations.
bus:
  host: xivo
  username: xivo
  password: xivo

# Consul configuration
consul:
  scheme: https
  host: xivo
  port: 8500
  verify: False
  token: c3b2ae2c52056c1c2212aa72c2e0dc63f2c95039da933a47d5144bdac704003a

# Discovery configuration
service_discovery:
  advertise_address: auto
  advertise_address_interface: eth0

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@xivo/asterisk

# AMI asterisk
ipbx_connection:
  ipaddress: xivo
