# Rest API
rest_api:
  http:
    listen: 0.0.0.0

# Agentd
agentd:
  host: xivo

# Provd
provd:
  host: xivo

# Dird (Directory daemon) connection informations.
dird:
  host: xivo

# xivo-auth (authentication daemon) connection informations.
auth:
    host: xivo

# Event bus (AMQP) connection informations.
bus:
  host: xivo
  username: xivo
  password: xivo

service_discovery:
  advertise_address: my_public_ip
  check_url: http://my_public_ip:9495/0.1/infos

# Database connection informations.
db_uri: postgresql://asterisk:proformatique@xivo/asterisk

# AMI asterisk
ipbx_connection:
  ipaddress: xivo
